

import { Declaration, DeclarationStatus, PolicyAlert, ChartData, Language } from './types';

export const MOCK_DECLARATIONS: Declaration[] = [
  {
    id: 'DEC-2023-8821',
    companyName: 'Global Tech Imports Ltd',
    submitDate: '2023-10-25 09:15',
    amount: 154000,
    currency: 'USD',
    status: DeclarationStatus.CLEARED,
    riskScore: 12,
    anomalies: [],
    documents: ['Invoice_8821.pdf', 'PackingList.pdf'],
    goodsType: 'Semiconductors',
    hsCode: '8542.31'
  },
  {
    id: 'DEC-2023-8822',
    companyName: 'Future Logistics Co',
    submitDate: '2023-10-25 10:30',
    amount: 42000,
    currency: 'USD',
    status: DeclarationStatus.AUDIT_REQUIRED,
    riskScore: 85,
    anomalies: ['HS Code Mismatch', 'Unusual Origin Port'],
    documents: ['Invoice_8822.pdf', 'Origin_Cert_v1.pdf', 'Bill_of_Lading.jpg'],
    goodsType: 'Textiles',
    hsCode: '6203.42'
  },
  {
    id: 'DEC-2023-8823',
    companyName: 'Oceanic Foods Inc',
    submitDate: '2023-10-25 11:45',
    amount: 89000,
    currency: 'EUR',
    status: DeclarationStatus.RISK_CHECK,
    riskScore: 45,
    anomalies: ['Price Fluctuation > 15%'],
    documents: ['Invoice_8823.pdf', 'SanitaryCert.pdf'],
    goodsType: 'Frozen Seafood',
    hsCode: '0303.89'
  },
  {
    id: 'DEC-2023-8824',
    companyName: 'Sunrise Electronics',
    submitDate: '2023-10-25 13:20',
    amount: 210500,
    currency: 'USD',
    status: DeclarationStatus.VALIDATING,
    riskScore: 5,
    anomalies: [],
    documents: ['Invoice_8824.pdf'],
    goodsType: 'Consumer Electronics',
    hsCode: '8517.13'
  }
];

export const POLICY_ALERTS: PolicyAlert[] = [
  {
    id: 'POL-001',
    title: 'New Cross-border E-commerce Regulation',
    date: '2023-10-24',
    severity: 'medium',
    description: 'Updated tax rates for specific electronic components effective Nov 1st. Please review HS Codes 8542.xx.'
  },
  {
    id: 'POL-002',
    title: 'System Maintenance Notice',
    date: '2023-10-20',
    severity: 'low',
    description: 'The Smart Tax Gateway will undergo maintenance on Sunday 2 AM - 4 AM.'
  }
];

export const PENDING_TASKS = [
  {
    id: 1,
    title: 'Confirm Tax Adjustment',
    desc: 'Policy update 2023-A4 affects your Q3 declaration.',
    fullDesc: 'According to the new Tax Policy 2023-A4 released yesterday, the VAT rate for digital service imports has been adjusted. Your Q3 declaration (ID: DEC-2023-Q3-001) contains items affected by this change. The system has pre-calculated a tax difference of $450.20.',
    actionText: 'Please review the changes and confirm the adjustment to proceed with the filing.',
    date: 'Today',
    status: 'urgent'
  },
  {
    id: 2,
    title: 'Upload Supplementary Docs',
    desc: 'Declaration #9921 requires origin certificate.',
    fullDesc: 'Customs has flagged Declaration #9921 for missing Origin Certification. This is required for the preferential tariff treatment claimed.',
    actionText: 'Please upload the scanned Certificate of Origin (Form A) to release the hold.',
    date: 'Yesterday',
    status: 'pending'
  },
  {
    id: 3,
    title: 'Quarterly Audit Review',
    desc: 'Routine check for compliance.',
    fullDesc: 'Your quarterly automated compliance review is ready. No major issues were found, but some minor HS Code optimizations are suggested.',
    actionText: 'Review the full report to improve your compliance score for the next quarter.',
    date: 'Oct 24',
    status: 'normal'
  }
];

export const VOLUME_DATA: ChartData[] = [
  { name: 'Mon', value: 400 },
  { name: 'Tue', value: 300 },
  { name: 'Wed', value: 550 },
  { name: 'Thu', value: 480 },
  { name: 'Fri', value: 620 },
  { name: 'Sat', value: 200 },
  { name: 'Sun', value: 150 },
];

export const RISK_DISTRIBUTION_DATA: ChartData[] = [
  { name: 'Low Risk (Green)', value: 75 },
  { name: 'Medium Risk (Yellow)', value: 20 },
  { name: 'High Risk (Red)', value: 5 },
];

export const TRANSLATIONS = {
  en: {
    app_name: "SmartTax",
    tagline: "Cross-border Intelligent Taxation & Compliance System",
    role_enterprise: "Enterprise User",
    role_official: "Tax Official",
    login_enterprise_title: "Enterprise Portal",
    login_enterprise_desc: "For import/export companies to submit declarations, track clearance status, and manage compliance risks.",
    login_enterprise_btn: "Enter as Enterprise",
    login_official_title: "Authority Workstation",
    login_official_desc: "For tax officials and customs officers to audit high-risk declarations, monitor anomalies, and manage policies.",
    login_official_btn: "Enter as Official",
    nav_dashboard: "Dashboard",
    nav_list: "My Declarations",
    nav_tracking: "Process Tracking",
    nav_audit: "Audit Queue",
    nav_risk: "Risk Monitor",
    nav_anomalies: "Anomalies",
    nav_settings: "Settings",
    switch_view: "Switch View",
    sign_out: "Sign Out",
    welcome_ent: "Digital Service Hall",
    welcome_tax: "Integrated Risk Command Center",
    system_online: "System Online",
    policy_alert: "Policy Update Alert",
    btn_active: "Active Processes",
    btn_my_dec: "My Declarations",
    btn_new: "New Submission",
    upload_title: "Upload Declaration Documents",
    upload_desc: "Upload Invoices, Contracts, or Manifests. Our smart engine will automatically extract data, validate HS Codes, and check for compliance.",
    upload_btn: "Select Files",
    processing: "Processing Document...",
    ocr_running: "Running OCR and Structural Parsing",
    declared_value: "Declared Value",
    live_status: "Live Status Tracking",
    settings_title: "System Settings",
    settings_lang: "Language / 语言",
    settings_algo: "Algorithm Parameters",
    settings_threshold: "Risk Threshold",
    settings_sampling: "Sampling Rate",
    kpi_total: "Total Declarations",
    kpi_high: "High Risk Alerts",
    kpi_auto: "Auto-Clearance Rate",
    chart_vol: "Weekly Declaration Volume",
    chart_risk: "Risk Distribution",
    audit_queue: "Priority Audit Queue",
    model_expl: "Model Explanation",
    rec_action: "Recommended Action",
    dec_summary: "Declaration Summary",
    step_draft: "Draft",
    step_ocr: "OCR Parsing",
    step_valid: "Rule Validation",
    step_risk: "Risk Model",
    step_clear: "Cleared",
    status_audit: "Audit Required",
    btn_view_docs: "View Documents",
    btn_start_audit: "Start Audit",
    btn_auditing: "Auditing...",
    btn_audited: "Verified",
    doc_viewer_title: "Associated Documents",
    anomalies_title: "Live Anomaly Detection",
    anomalies_desc: "Real-time stream of data anomalies detected from port sensors and declaration logic.",
    feed_col_time: "TIMESTAMP",
    feed_col_event: "EVENT TYPE",
    feed_col_origin: "ORIGIN",
    feed_col_status: "STATUS",
    feed_status_detected: "DETECTED",
    feed_status_analyzing: "ANALYZING",
    company_profile: "Company Profile",
    tax_id: "Tax ID",
    notif_pref: "Notification Preferences",
    notif_email: "Email alerts for policy updates",
    notif_sms: "SMS alerts for audit requirements",
    
    // New Translations
    pending_tasks: "Pending Tasks",
    task_active: "Active",
    compliance_score: "Compliance Score",
    compliance_desc: "Your compliance rating is excellent. Low audit probability this month.",
    toast_audit_complete: "Audit Completed. Report Generated.",
    modal_urgent: "Urgent",
    modal_description: "DESCRIPTION",
    modal_action_req: "Action Required",
    modal_close: "Close",
    modal_process: "Process Now",
    btn_processing: "Processing...",
    toast_task_complete: "Task Completed Successfully.",
    
    // Advanced Modal States
    modal_processing_title: "Processing Request...",
    modal_processing_desc: "Validating rules and submitting declaration updates.",
    modal_success_title: "Submission Successful",
    modal_success_desc: "The task has been processed and logged. The system rule engine has approved the changes.",
    modal_trans_id: "Transaction ID",
    btn_done: "Done"
  },
  cn: {
    app_name: "智慧税务",
    tagline: "跨境智能税务与合规系统",
    role_enterprise: "企业用户",
    role_official: "税务官员",
    login_enterprise_title: "企业服务门户",
    login_enterprise_desc: "面向进出口企业，提供报关申报提交、通关状态追踪及合规风险管理服务。",
    login_enterprise_btn: "企业入口",
    login_official_title: "税务监管工作台",
    login_official_desc: "面向税务及海关人员，提供高风险申报审核、异常监测及政策管理功能。",
    login_official_btn: "官员入口",
    nav_dashboard: "仪表盘",
    nav_list: "我的申报",
    nav_tracking: "流程追踪",
    nav_audit: "审核队列",
    nav_risk: "风险监控",
    nav_anomalies: "异常检测",
    nav_settings: "系统设置",
    switch_view: "切换视图",
    sign_out: "退出登录",
    welcome_ent: "数字服务大厅",
    welcome_tax: "综合风险指挥中心",
    system_online: "系统在线",
    policy_alert: "政策更新提醒",
    btn_active: "进行中流程",
    btn_my_dec: "我的申报单",
    btn_new: "新建申报",
    upload_title: "上传申报单证",
    upload_desc: "上传发票、合同或舱单。我们的智能引擎将自动提取数据、校验HS编码并检查合规性。",
    upload_btn: "选择文件",
    processing: "正在处理文档...",
    ocr_running: "正在运行OCR与结构化解析",
    declared_value: "申报金额",
    live_status: "实时状态追踪",
    settings_title: "系统设置",
    settings_lang: "语言 / Language",
    settings_algo: "算法模型参数",
    settings_threshold: "风险判定阈值",
    settings_sampling: "随机抽样率",
    kpi_total: "今日申报总数",
    kpi_high: "高风险警报",
    kpi_auto: "自动通关率",
    chart_vol: "周申报量趋势",
    chart_risk: "风险分布",
    audit_queue: "优先审核队列",
    model_expl: "模型解释",
    rec_action: "推荐措施",
    dec_summary: "申报摘要",
    step_draft: "草稿",
    step_ocr: "OCR解析",
    step_valid: "规则校验",
    step_risk: "风险模型",
    step_clear: "已通关",
    status_audit: "需审核",
    btn_view_docs: "查看单证",
    btn_start_audit: "开始审核",
    btn_auditing: "审核中...",
    btn_audited: "审核完成",
    doc_viewer_title: "关联单证文件",
    anomalies_title: "实时异常检测",
    anomalies_desc: "来自港口传感器和申报逻辑的实时数据异常流。",
    feed_col_time: "时间戳",
    feed_col_event: "事件类型",
    feed_col_origin: "来源地",
    feed_col_status: "状态",
    feed_status_detected: "已检测",
    feed_status_analyzing: "分析中",
    company_profile: "企业资料",
    tax_id: "纳税人识别号",
    notif_pref: "通知偏好",
    notif_email: "接收政策更新邮件",
    notif_sms: "接收审核短信通知",

    // New Translations
    pending_tasks: "待办任务",
    task_active: "进行中",
    compliance_score: "合规评分",
    compliance_desc: "您的合规评级为优秀。本月被稽查概率较低。",
    toast_audit_complete: "审核完成。报告已自动生成并归档。",
    modal_urgent: "紧急",
    modal_description: "详细说明",
    modal_action_req: "需要采取措施",
    modal_close: "关闭",
    modal_process: "立即处理",
    btn_processing: "处理中...",
    toast_task_complete: "任务处理成功",

    // Advanced Modal States
    modal_processing_title: "正在处理请求...",
    modal_processing_desc: "正在校验规则并提交申报更新。",
    modal_success_title: "提交成功",
    modal_success_desc: "任务已处理并记录日志。系统规则引擎已批准变更。",
    modal_trans_id: "交易ID",
    btn_done: "完成"
  }
};